#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "backend.h"
#include "serial.h"
#include "vquest.h"        /* FP_*, LUT_SIZE, Point3DInt, PhysicsState, … */

#include "gen_tables.h"   /* kSinQuarter[], kModelVerts[], kModelEdges[] (generated) */

/* Full sine table expanded at startup from the baked quarter wave
 * (kSinQuarter, generated by gen_tables.c) — integer-only:
 *
 *   sin[LUT_SIZE/2 - i] =  sin[i]          (mirror around π/2)
 *   sin[LUT_SIZE/2 + i] = -sin[i]          (half-wave antisymmetry)
 *   sin[LUT_SIZE   - i] = -sin[i]
 *
 * No cosine table: cos(a) = sin(a + LUT_SIZE/4), folded into fastCos. */
static int16_t sinLUT[LUT_SIZE];

static void lut_init(void) {
    uint16_t i;
    for (i = 0; i <= LUT_SIZE / 4; i++) {
        int16_t v = kSinQuarter[i];
        sinLUT[i]                              =  v;
        sinLUT[LUT_SIZE / 2 - i]               =  v;
        sinLUT[LUT_SIZE / 2 + i]               = (int16_t)(-v);
        sinLUT[(LUT_SIZE - i) & (LUT_SIZE-1)] = (int16_t)(-v);
    }
}

static inline int16_t fastSin(int16_t angle) {
    return sinLUT[angle & (LUT_SIZE-1)];
}

static inline int16_t fastCos(int16_t angle) {
    return sinLUT[(angle + LUT_SIZE / 4) & (LUT_SIZE-1)];
}

/* Fixed-point multiply: (a * b) >> FP_SHIFT.
 * GCC m68k emits muls.w (~70 cycles) + asr.l #10.
 * Exact integer result — no LUT quantization error. */
static inline int16_t mul_fp(int16_t a, int16_t b) {
    return (int16_t)(((int32_t)a * b) >> FP_SHIFT);
}

#include "render.c"    /* 3-D rendering pipeline (unity include) */
#include "physics.c"   /* game logic and state machine (unity include) */

static void draw_press_fire(void) {
    const Seg * const kPF[] = {
        seg_P, seg_R, seg_E, seg_S, seg_S, NULL,
        seg_F, seg_I, seg_R, seg_E, NULL,
        seg_T, seg_O, NULL,
        seg_S, seg_T, seg_A, seg_R, seg_T
    };
    lines_reset();
    draw_seg_array(kPF, 77, 180, FONT_MED_SX, FONT_MED_SY, FONT_MED_STEP, 6);
    memset(&gLines[gNLines], 0, sizeof(Line));
    backend_draw_alien_lines(gLines, gNLines);   /* into drawing buffer */
    backend_present(0, 0);                        /* swap */
    backend_draw_alien_lines(gLines, gNLines);   /* into the other buffer */
}

int main(int argc, char *argv[]) {
    int16_t angleY = 0, angleX = 0;
    int16_t angleYinc, angleXinc;
    PhysicsState ps = { CAM_Y_INIT, CAM_X_INIT, 0, 0, 0 };
    int16_t z_phase = 0;
    uint16_t frame         = 0;
    uint16_t min_frame     = 0;
    uint16_t max_frame     = 0;   /* 0 = no limit (replaces -1 sentinel) */
    int16_t crash_timer   = 0;
    int16_t strip_dist    = 0;   /* z-distance to landing strip; counts down each frame */
    int16_t strip_x       = 0;   /* lateral world position of landing strip             */
    int16_t alien_x[ALIEN_COUNT]       = {0};
    int16_t alien_z[ALIEN_COUNT]       = {0};
    bool    alien_alive[ALIEN_COUNT]   = {0};
    int16_t missile_x[MISSILE_COUNT]   = {0};
    int16_t missile_z[MISSILE_COUNT]   = {0};
    bool    missile_alive[MISSILE_COUNT] = {0};
/* Frames without a peer packet before the bot takes over the remote slot
 * (~1s).  Peers send every frame once paired, so any stall past this is a
 * real loss; the first real packet hands control back to the wire peer. */
#define REMOTE_TIMEOUT_FRAMES 50
/* Consecutive packets carrying the KILL bit after our missile hits the peer,
 * so a lost byte cannot drop the kill (receiver edge-triggers on it). */
#define KILL_REPEAT 8
    RemoteState remote = {0};      /* last known peer/bot state            */
    RemoteState rs_in;             /* scratch for serial_recv/bot_update   */
    int16_t remote_idle  = REMOTE_TIMEOUT_FRAMES;  /* saturating; starts timed-out */
    int16_t rmissile_x[MISSILE_COUNT]    = {0};    /* peer missiles, local frame */
    int16_t rmissile_z[MISSILE_COUNT]    = {0};
    bool    rmissile_alive[MISSILE_COUNT] = {0};
    int16_t kill_pending = 0;      /* outgoing KILL packets left to send   */
    bool    kill_latched = false;  /* edge detector for incoming KILL      */
    Bot     bot;
    bool    bot_enabled;
    int16_t cam_zspeed    = CAM_ZSPEED_BASE;
    int16_t round         = 1;
    int16_t takeoff_timer = TAKEOFF_FRAMES_BASE;
    GameState state       = STATE_TAKEOFF;

    if (argc >= 2) min_frame = (uint16_t)atoi(argv[1]);
    if (argc >= 3) max_frame = (uint16_t)atoi(argv[2]);
    /* "nobot" keeps the remote slot empty without a peer — used by the
     * deterministic race-mode tests (env vars don't survive hatari). */
    bot_enabled = !(argc >= 6 && strcmp(argv[5], "nobot") == 0);
    bot_init(&bot);

    backend_init();
    serial_init(argc >= 4 ? argv[3] : NULL, argc >= 5 ? argv[4] : NULL);
    gLines = malloc((MAX_DRAW_LINES + 1) * sizeof(Line));
    lut_init();
    strip_x = next_strip_x(round, frame);

    /* Intro: reveal title + subtitle one letter at a time; any key skips.
     *
     * Credits live on the grid plane (plane 0, blue).  On Atari the display is
     * double-buffered: we draw credits to the current drawing buffer, present
     * (swap), then draw again so both physical buffers carry the credits.
     * After that the intro loop just calls backend_present() — no backend_clear()
     * — so plane 0 is never wiped and the credits persist without any redraw.
     * HUD letters (plane 2, green) use backend_hud_line() which draws directly
     * into both buffers on Atari and draws immediately on SDL, so they too
     * accumulate without a clear cycle.
     * Credits auto-disappear when the main game loop's first backend_clear()
     * wipes plane 0+1 (happens on the first game frame). */
#define INTRO_LETTER_FRAMES 6
#define INTRO_NSTEPS (HUD_NCHARS > HUD_NSUB ? HUD_NCHARS : HUD_NSUB)
    {
        int8_t k = 0;

        /* Draw credits into plane 0 of both buffers. */
        lines_reset();
        credits_render();
        memset(&gLines[gNLines], 0, sizeof(Line));   /* sentinel for SegmentedMultiLine */
        backend_clear();
        backend_draw_lines(gLines, gNLines);
        backend_present(0, 0);                       /* swap: other buffer is now drawing */
        backend_draw_lines(gLines, gNLines);         /* same credits into the other buffer */

        hud_begin();
        while (k < INTRO_NSTEPS) {
            int8_t j;
            int drew = 0;
            if (k < HUD_NCHARS)     drew |= hud_draw_letter(k);
            if (k < HUD_NSUB)       drew |= hud_draw_subletter(k);
            k++;
            if (!drew) continue;    /* both are spaces: skip pause */
            for (j = 0; j < INTRO_LETTER_FRAMES; j++)
                backend_present(0, 0);
        }
        hud_draw_tally(1);
    }

    build_grid();

    /* Convert rad/frame speeds to LUT-index increments */
    angleYinc = (int16_t)(0.16 * FP_ONE);
    angleXinc = (int16_t)(-0.13 * FP_ONE);
    angleYinc = (int16_t)((int32_t)angleYinc * LUT_SIZE / (2L * FP_ONE * 31415 / 10000));
    angleXinc = (int16_t)((int32_t)angleXinc * LUT_SIZE / (2L * FP_ONE * 31415 / 10000));

    /* "PRESS FIRE TO START" — seed alien plane of both framebuffers once, then
     * wait.  Glow animates via palette on each backend_present(); no pixel redraw. */
    {
        draw_press_fire();
        for (;;) {
            uint8_t keys = backend_get_keys();
            if (keys & KEY_QUIT) { backend_cleanup(); return 0; }
            if (keys & KEY_FIRE) {
                backend_snd_switch(SND_MAIN);
                backend_snd_sfx(SND_FIRE);
                break;
            }
            backend_present(0, 0);
        }
    }
    for (;;) {
        uint8_t keys = backend_get_keys();
        if (keys & KEY_QUIT) break;
        if (max_frame != 0 && frame > max_frame) break;

        /* Grid always scrolls */
        z_phase = (int16_t)(z_phase + cam_zspeed);
        if (z_phase >= GRID_ZSTEP) z_phase = (int16_t)(z_phase - GRID_ZSTEP);

        bool flash = false;
        bool fired = false;
        const RenderFlags *rf = &kStateFlags[state];

        int prev_state = state;
        switch (state) {
        case STATE_TAKEOFF:
            state = state_takeoff(&takeoff_timer, &ps,
                                  &strip_dist, round,
                                  alien_x, alien_z, alien_alive, missile_alive, keys);
            break;
        case STATE_CRUISE:
            state = state_cruise(&strip_dist, &ps, &cam_zspeed,
                                 alien_z, alien_alive,
                                 missile_x, missile_z, missile_alive, &fired, keys);
            break;
        case STATE_LANDING:
            state = state_landing(&ps,
                                  &strip_dist, &strip_x, &round, &cam_zspeed,
                                  alien_z, alien_alive, keys, frame);
            break;
        case STATE_CRASH:
            state = state_crash(&flash, &crash_timer, &round,
                                &takeoff_timer, &cam_zspeed, &strip_x,
                                &ps, frame);
            break;
        case STATE_SUCCESS:
            state = state_success(&angleY, &angleX,
                                  &ps,
                                  &takeoff_timer, angleYinc, angleXinc, keys);
            break;
        }

        /* Alien contact: live alien crossing z=0 within FP_ONE laterally → crash */
        if ((state == STATE_CRUISE || state == STATE_LANDING) &&
            alien_hit_player(ps.cam_x, cam_zspeed, alien_x, alien_z, alien_alive)) {
            state = STATE_CRASH;
        }

        /* Safety clamp: allow wider roam during cruise; grid uses cam_x only for
         * horizontal lines (world x fixed) so ±6 is safe.  Strip rendering guards
         * cam_x_rel separately below (strip can be up to STRIP_X_MAX away).
         * Clamped before the wire too: the 14-bit packet field relies on it. */
        if (ps.cam_x >  6 * FP_ONE) ps.cam_x =  (int16_t)(6 * FP_ONE);
        if (ps.cam_x < -6 * FP_ONE) ps.cam_x = -(int16_t)(6 * FP_ONE);

        /* Per-leg race coordinate shared with the peer: how far down the
         * approach we are.  0 during takeoff so both players start each leg
         * level; the strip distance is the common course on both machines.
         * Capped at the course length (strip_dist runs negative during the
         * final descent) so rel_z differences always fit int16_t. */
        uint16_t my_progress = (state == STATE_CRUISE || state == STATE_LANDING)
                             ? (uint16_t)(LANDING_APPROACH_DIST - strip_dist) : 0;
        if (my_progress > LANDING_APPROACH_DIST) my_progress = LANDING_APPROACH_DIST;

        /* Advance missiles every frame so they expire at the horizon regardless
         * of state.  Peer missiles run through the same sim against the same
         * deterministic alien field, so both machines agree on alien kills. */
        update_missiles(cam_zspeed, missile_x, missile_z, missile_alive,
                        alien_x,   alien_z,   alien_alive);
        update_missiles(cam_zspeed, rmissile_x, rmissile_z, rmissile_alive,
                        alien_x,   alien_z,   alien_alive);

        /* Remote slot: a serial peer when one is talking, the bot otherwise. */
        {
            bool got = serial_recv(&rs_in);
            if (got)                                       remote_idle = 0;
            else if (remote_idle < REMOTE_TIMEOUT_FRAMES)  remote_idle++;
            bool bot_active = bot_enabled && remote_idle >= REMOTE_TIMEOUT_FRAMES;
            if (!got && bot_active) {
                bot_update(&bot, &rs_in, alien_x, alien_z, alien_alive,
                           my_progress, ps.cam_x, frame);
                got = true;
            }
            if (got) {
                remote = rs_in;
                if (remote.fire && remote.state != RS_DEAD) {
                    int16_t muzzle_z = (int16_t)((int16_t)remote.progress
                                                 - (int16_t)my_progress + HLINE_ZMIN);
                    int i;
                    for (i = 0; i < MISSILE_COUNT; i++)
                        if (!rmissile_alive[i]) {
                            rmissile_x[i]     = remote.cam_x;
                            rmissile_z[i]     = muzzle_z;
                            rmissile_alive[i] = true;
                            break;
                        }
                }
                /* Their missile hit us (shooter-authoritative, edge-triggered). */
                if (remote.kill && !kill_latched &&
                    (state == STATE_CRUISE || state == STATE_LANDING))
                    state = STATE_CRASH;
                kill_latched = remote.kill;
            }

            /* Bot shots at us are resolved locally (no wire to carry a KILL):
             * its missiles fly forward in our frame and cross us at z≈0. */
            if (bot_active && (state == STATE_CRUISE || state == STATE_LANDING) &&
                missiles_hit_ghost(cam_zspeed, rmissile_x, rmissile_z, rmissile_alive,
                                   ps.cam_x, 1, (int16_t)(FP_ONE / 4)))
                state = STATE_CRASH;

            /* Our missiles vs the ghost: shooter detects the hit and tells the
             * peer via the KILL bit (the bot is killed directly).  The local
             * RS_DEAD override hides the ghost until its own state catches up. */
            if ((remote_idle < REMOTE_TIMEOUT_FRAMES || bot_active) &&
                remote.state != RS_DEAD &&
                missiles_hit_ghost(cam_zspeed, missile_x, missile_z, missile_alive,
                                   remote.cam_x,
                                   (int16_t)((int16_t)remote.progress - (int16_t)my_progress),
                                   (int16_t)(ALIEN_SCALE_W / FOCAL))) {
                backend_snd_sfx(SND_ENMYHIT);
                if (bot_active) bot_kill(&bot);
                else            kill_pending = KILL_REPEAT;
                remote.state = RS_DEAD;
            }
        }

        /* Sound transitions last: a crash can come from the state machine,
         * an alien, or the peer's KILL — all of the above. */
        if (state == STATE_CRASH && prev_state != STATE_CRASH) {
            crash_timer = backend_snd_switch(SND_GAMEOVER);
        }
        if (state == STATE_TAKEOFF && prev_state == STATE_CRASH)
            backend_snd_switch(SND_MAIN);

        /* Beacon until a peer is heard: sending costs 7 BIOS traps on Atari,
         * so single-player only pays them every 16th frame.  Both sides
         * beacon, so pairing completes within ~0.3s; once paired, send every
         * frame for smooth ghosting (and fall back to beaconing if the peer
         * goes quiet past the ghost timeout). */
        if (remote_idle < REMOTE_TIMEOUT_FRAMES || (frame & 15) == 0) {
            RemoteState out;
            out.state    = state == STATE_CRUISE  ? RS_CRUISE
                         : state == STATE_LANDING ? RS_LANDING
                         : state == STATE_CRASH   ? RS_DEAD
                         : RS_TAKEOFF;             /* SUCCESS: grounded, next leg */
            out.fire     = fired;
            out.kill     = kill_pending > 0;
            out.cam_x    = ps.cam_x;
            out.progress = my_progress;
            out.alt      = ps.cam_y;
            serial_send(&out);
            if (kill_pending > 0) kill_pending--;
        }

        backend_set_flash(flash);
        frame++;
        if (frame < min_frame) continue;
        backend_clear();
        draw_world_plane(rf, ps.cam_y, z_phase, ps.cam_x,
                         strip_dist, strip_x);
        {
            /* Ghost placement: race-relative depth, clamped near so a peer
             * alongside (takeoff, photo-finish) is still drawn; hidden once
             * clearly behind us — the leader cannot see the chaser. */
            int16_t rel_z = (int16_t)((int16_t)remote.progress - (int16_t)my_progress);
            /* a peer is talking, or the bot is filling the slot */
            bool peer_on  = (remote_idle < REMOTE_TIMEOUT_FRAMES || bot_enabled) &&
                            remote.state != RS_DEAD;
            bool show_ghost = peer_on && rel_z > -REMOTE_Z_NEAR && rf->remote_player;
            int16_t ghost_z = rel_z < REMOTE_Z_NEAR ? REMOTE_Z_NEAR
                            : rel_z > GRID_ZFAR     ? GRID_ZFAR : rel_z;
            draw_alien_plane(rf->logo, angleY, angleX,
                             rf->aliens, alien_x, alien_z, alien_alive,
                             missile_x, missile_z, missile_alive, ps.cam_x,
                             rf->takeoff_strip, rf->landing_strip,
                             takeoff_timer, strip_dist, strip_x, ps.cam_y, z_phase,
                             cam_zspeed,
                             show_ghost, remote.cam_x, ghost_z, remote.alt,
                             rf->remote_player,
                             rmissile_x, rmissile_z, rmissile_alive);
        }
        backend_present(angleY, angleX);
    }

    serial_cleanup();
    backend_cleanup();
    return 0;
}
